/* generated by rust_qt_binding_generator */
#![allow(unknown_lints)]
#![allow(mutex_atomic, needless_pass_by_value)]
use libc::{c_char, c_ushort, c_int};
use std::slice;
use std::char::decode_utf16;

use std::sync::{Arc, Mutex};
use std::ptr::null;

use backend::accounts::*;

#[repr(C)]
pub struct COption<T> {
    data: T,
    some: bool,
}

impl<T> COption<T> {
    #![allow(dead_code)]
    fn into(self) -> Option<T> {
        if self.some {
            Some(self.data)
        } else {
            None
        }
    }
}

impl<T> From<Option<T>> for COption<T>
where
    T: Default,
{
    fn from(t: Option<T>) -> COption<T> {
        if let Some(v) = t {
            COption {
                data: v,
                some: true,
            }
        } else {
            COption {
                data: T::default(),
                some: false,
            }
        }
    }
}


pub enum QString {}

fn set_string_from_utf16(s: &mut String, str: *const c_ushort, len: c_int) {
    let utf16 = unsafe { slice::from_raw_parts(str, to_usize(len)) };
    let characters = decode_utf16(utf16.iter().cloned())
        .map(|r| r.unwrap());
    s.clear();
    s.extend(characters);
}



#[repr(C)]
#[derive(PartialEq, Eq, Debug)]
pub enum SortOrder {
    Ascending = 0,
    Descending = 1,
}

#[repr(C)]
pub struct QModelIndex {
    row: c_int,
    internal_id: usize,
}


fn to_usize(n: c_int) -> usize {
    if n < 0 {
        panic!("Cannot cast {} to usize", n);
    }
    n as usize
}


fn to_c_int(n: usize) -> c_int {
    if n > c_int::max_value() as usize {
        panic!("Cannot cast {} to c_int", n);
    }
    n as c_int
}


pub struct AccountsQObject {}

#[derive(Clone)]
pub struct AccountsEmitter {
    qobject: Arc<Mutex<*const AccountsQObject>>,
    new_data_ready: fn(*const AccountsQObject),
}

unsafe impl Send for AccountsEmitter {}

impl AccountsEmitter {
    fn clear(&self) {
        *self.qobject.lock().unwrap() = null();
    }
    pub fn new_data_ready(&self) {
        let ptr = *self.qobject.lock().unwrap();
        if !ptr.is_null() {
            (self.new_data_ready)(ptr);
        }
    }
}

#[derive(Clone)]
pub struct AccountsList {
    qobject: *const AccountsQObject,
    layout_about_to_be_changed: fn(*const AccountsQObject),
    layout_changed: fn(*const AccountsQObject),
    data_changed: fn(*const AccountsQObject, usize, usize),
    begin_reset_model: fn(*const AccountsQObject),
    end_reset_model: fn(*const AccountsQObject),
    begin_insert_rows: fn(*const AccountsQObject, usize, usize),
    end_insert_rows: fn(*const AccountsQObject),
    begin_move_rows: fn(*const AccountsQObject, usize, usize, usize),
    end_move_rows: fn(*const AccountsQObject),
    begin_remove_rows: fn(*const AccountsQObject, usize, usize),
    end_remove_rows: fn(*const AccountsQObject),
}

impl AccountsList {
    pub fn layout_about_to_be_changed(&self) {
        (self.layout_about_to_be_changed)(self.qobject);
    }
    pub fn layout_changed(&self) {
        (self.layout_changed)(self.qobject);
    }
    pub fn data_changed(&self, first: usize, last: usize) {
        (self.data_changed)(self.qobject, first, last);
    }
    pub fn begin_reset_model(&self) {
        (self.begin_reset_model)(self.qobject);
    }
    pub fn end_reset_model(&self) {
        (self.end_reset_model)(self.qobject);
    }
    pub fn begin_insert_rows(&self, first: usize, last: usize) {
        (self.begin_insert_rows)(self.qobject, first, last);
    }
    pub fn end_insert_rows(&self) {
        (self.end_insert_rows)(self.qobject);
    }
    pub fn begin_move_rows(&self, first: usize, last: usize, destination: usize) {
        (self.begin_move_rows)(self.qobject, first, last, destination);
    }
    pub fn end_move_rows(&self) {
        (self.end_move_rows)(self.qobject);
    }
    pub fn begin_remove_rows(&self, first: usize, last: usize) {
        (self.begin_remove_rows)(self.qobject, first, last);
    }
    pub fn end_remove_rows(&self) {
        (self.end_remove_rows)(self.qobject);
    }
}

pub trait AccountsTrait {
    fn new(emit: AccountsEmitter, model: AccountsList) -> Self;
    fn emit(&self) -> &AccountsEmitter;
    fn row_count(&self) -> usize;
    fn insert_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn remove_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn can_fetch_more(&self) -> bool {
        false
    }
    fn fetch_more(&mut self) {}
    fn sort(&mut self, u8, SortOrder) {}
    fn bank(&self, index: usize) -> &str;
    fn set_bank(&mut self, index: usize, String) -> bool;
    fn name(&self, index: usize) -> &str;
    fn set_name(&mut self, index: usize, String) -> bool;
    fn uuid(&self, index: usize) -> &str;
    fn set_uuid(&mut self, index: usize, String) -> bool;
}

#[no_mangle]
pub extern "C" fn accounts_new(
    accounts: *mut AccountsQObject,
    accounts_new_data_ready: fn(*const AccountsQObject),
    accounts_layout_about_to_be_changed: fn(*const AccountsQObject),
    accounts_layout_changed: fn(*const AccountsQObject),
    accounts_data_changed: fn(*const AccountsQObject, usize, usize),
    accounts_begin_reset_model: fn(*const AccountsQObject),
    accounts_end_reset_model: fn(*const AccountsQObject),
    accounts_begin_insert_rows: fn(*const AccountsQObject, usize, usize),
    accounts_end_insert_rows: fn(*const AccountsQObject),
    accounts_begin_move_rows: fn(*const AccountsQObject, usize, usize, usize),
    accounts_end_move_rows: fn(*const AccountsQObject),
    accounts_begin_remove_rows: fn(*const AccountsQObject, usize, usize),
    accounts_end_remove_rows: fn(*const AccountsQObject),
) -> *mut Accounts {
    let accounts_emit = AccountsEmitter {
        qobject: Arc::new(Mutex::new(accounts)),
        new_data_ready: accounts_new_data_ready,
    };
    let model = AccountsList {
        qobject: accounts,
        layout_about_to_be_changed: accounts_layout_about_to_be_changed,
        layout_changed: accounts_layout_changed,
        data_changed: accounts_data_changed,
        begin_reset_model: accounts_begin_reset_model,
        end_reset_model: accounts_end_reset_model,
        begin_insert_rows: accounts_begin_insert_rows,
        end_insert_rows: accounts_end_insert_rows,
        begin_move_rows: accounts_begin_move_rows,
        end_move_rows: accounts_end_move_rows,
        begin_remove_rows: accounts_begin_remove_rows,
        end_remove_rows: accounts_end_remove_rows,
    };
    let d_accounts = Accounts::new(accounts_emit, model);
    Box::into_raw(Box::new(d_accounts))
}

#[no_mangle]
pub unsafe extern "C" fn accounts_free(ptr: *mut Accounts) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn accounts_row_count(ptr: *const Accounts) -> c_int {
    to_c_int((&*ptr).row_count())
}
#[no_mangle]
pub unsafe extern "C" fn accounts_insert_rows(ptr: *mut Accounts, row: c_int, count: c_int) -> bool {
    (&mut *ptr).insert_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn accounts_remove_rows(ptr: *mut Accounts, row: c_int, count: c_int) -> bool {
    (&mut *ptr).remove_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn accounts_can_fetch_more(ptr: *const Accounts) -> bool {
    (&*ptr).can_fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn accounts_fetch_more(ptr: *mut Accounts) {
    (&mut *ptr).fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn accounts_sort(
    ptr: *mut Accounts,
    column: u8,
    order: SortOrder,
) {
    (&mut *ptr).sort(column, order)
}

#[no_mangle]
pub unsafe extern "C" fn accounts_data_bank(
    ptr: *const Accounts, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.bank(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

#[no_mangle]
pub unsafe extern "C" fn accounts_set_data_bank(
    ptr: *mut Accounts, row: c_int,
    s: *const c_ushort, len: c_int,
) -> bool {
    let o = &mut *ptr;
    let mut v = String::new();
    set_string_from_utf16(&mut v, s, len);
    o.set_bank(to_usize(row), v)
}

#[no_mangle]
pub unsafe extern "C" fn accounts_data_name(
    ptr: *const Accounts, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.name(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

#[no_mangle]
pub unsafe extern "C" fn accounts_set_data_name(
    ptr: *mut Accounts, row: c_int,
    s: *const c_ushort, len: c_int,
) -> bool {
    let o = &mut *ptr;
    let mut v = String::new();
    set_string_from_utf16(&mut v, s, len);
    o.set_name(to_usize(row), v)
}

#[no_mangle]
pub unsafe extern "C" fn accounts_data_uuid(
    ptr: *const Accounts, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.uuid(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

#[no_mangle]
pub unsafe extern "C" fn accounts_set_data_uuid(
    ptr: *mut Accounts, row: c_int,
    s: *const c_ushort, len: c_int,
) -> bool {
    let o = &mut *ptr;
    let mut v = String::new();
    set_string_from_utf16(&mut v, s, len);
    o.set_uuid(to_usize(row), v)
}
